package chessserver.Enums;

public enum ServerResponseType {
    CLIENTVAIDATIONSUCESS,
    INVALIDOPERATION,
    SQLERROR,
    ENTEREDGAME,
    GAMECLOSED,
    GAMEFINISHED,
    GAMEMOVEFROMOPPONENT,
    CHATFROMOPPONENT,
    SQLSUCESS,
    INCOMINGFRIENDREQUEST,
    SQLMESSAGE,
    ELOUPDATE,
    SERVERRESPONSEACTIONREQUEST, ACCEPTEDFRIENDREQUEST, CLOSEDSUCESS, TIMETICK;
}
