package chessserver;

public enum ServerResponseType {
    CLIENTVAIDATIONSUCESS,
    CLIENTVALIDATIONFAIL,
    INVALIDOPERATION,
    SQLERROR,
    ENTEREDGAME,
    INWAITINGPOOL,
    LEFTGAMESUCESS,
    GAMECLOSED,
    TOTALPLAYERCOUNT,
    NUMBEROFPOOLERS,
    POOLERS,
    GAMEMOVEFROMOPPONENT,
    CHATFROMOPPONENT,
    DATARESPONSE, ELOUPDATE
}
