package chessserver;

public enum ServerResponseType {
    CLIENTVAIDATIONSUCESS,
    CLIENTVALIDATIONFAIL,
    INVALIDOPERATION,
    ENTEREDGAME,
    INWAITINGPOOL,
    LEFTGAMESUCESS,
    GAMECLOSED,
    TOTALPLAYERCOUNT,
    NUMBEROFPOOLERS,
    POOLERS,
    TURNINDICATOR,
    GAMEMOVEFROMOPPONENT,
    CHATFROMOPPONENT,
    ELOUPDATE;
}
