/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chessengine;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

public class App extends Application {

    public static mainScreenController controller;
    private final String startUrl = "/FxmlFiles/StartScreen.fxml";
    private final String mainUrl = "/FxmlFiles/MainScreen.fxml";
    private static Stage mainStage;

    private static Scene mainScene;
    private static Parent startRoot;
    private static Parent mainRoot;



    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args){
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        mainStage = primaryStage;
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(App.class.getResource(mainUrl));
            fxmlLoader.setControllerFactory(c -> setMainScreenController()); // Set controller factory
            mainRoot = fxmlLoader.load();
            FXMLLoader fxmlLoader2 = new FXMLLoader(App.class.getResource(startUrl));
            fxmlLoader2.setControllerFactory(c -> new StartScreenController()); // Set controller factory
            startRoot = fxmlLoader2.load();


        } catch (IOException e) {
            e.printStackTrace();
        }
        mainScene = new Scene(startRoot);

        primaryStage.setScene(mainScene);
        primaryStage.show();
    }


    private mainScreenController setMainScreenController(){
        controller = new mainScreenController();
        return controller;
    }

    public static void changeScene(boolean isStart){
        if(isStart){
            mainScene.setRoot(startRoot);
        }
        else{
            mainScene.setRoot(mainRoot);
        }
    }




}
