- name: difficulty
  description: Difficulty level of the game
  defaultValue: 1
  options: 1-3

#- name: musicVolume
#  description: Volume of the background music
#  defaultValue: 0.5
#  options:
#    min: 0.0
#    max: 1.0
#    step: 0.1
#
#- name: fullscreen
#  description: Whether the game should start in fullscreen
#  defaultValue: true
#  options:
#    - true
#    - false
#
#- name: resolution
#  description: List of supported screen resolutions
#  defaultValue: 1920x1080
#  options:
#    - 1280x720
#    - 1600x900
#    - 1920x1080
#    - 2560x1440
